server:
  port: 8080
  #servlet:
    #context-path: /mgr
      #session:
    #timeout: 10

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://10.66.254.201:3306/zxdx_tms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql:replication://106.14.15.5:13333,106.14.15.5:13333/tms?useUnicode=true&characterEncoding=UTF-8&autoReconnect=false&useSSL=false&failOverReadOnly=true&loadBalanceStrategy=random&readFromMasterWhenNoSlaves=true&secondsBeforeRetryMaster=1&retriesAllDown=1&serverTimezone=Asia/Shanghai
    username: zxdx_
    password: zxdx_
    initialSize: 5 #初始化连接数
    minIdle: 5 #最小空闲数
    maxActive: 20 #最大连接数
    maxWait: 60000 #最大等待时长
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    logSlowSql: true
  thymeleaf:
    encoding: utf-8
    mode: HTML5
    cache: false
    #prefix: classpath:/templates/
    #suffix: .html
    #resources:
    #static-locations: classpath:/static
  mvc:
    static-path-pattern: /static/**
      #session:
      #  store-type: redis
      #  timeout: 10000
      #  redis:
      #    flush-mode: immediate
      #cleanup-cron: 0/5 * * * * ?
  jta:
    enabled: false #禁止JTA自动配置

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mgr.domain
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl








